# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David O'Dey | Web Designer & Front End Developer | Cave Creek Arizona
email: dodey@icloud.com
description: I have a strong passion for web standards, and creating uniquely awesome user experiences that can be accessed on all devices.
baseurl: "/~dodey/dev/jekyll/jekyll-davidodey/_site"
url: "" # the base hostname & protocol for your site
twitter_username: davdey
github_username:  davodey

# Build settings
markdown: kramdown
