# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David O'Dey | Web Designer & UI Developer | Phoenix Arizona
email: dodey@icloud.com
description: I have a strong passion for web standards, and creating uniquely awesome user experiences that can be accessed on all devices.
twitter_username: davdey
github_username:  davodey
permalink: /:categories/:title
excerpt_separator: "<!--more-->"
# Build settings
markdown: kramdown

blog_name:         Leveling up with David O'Dey UI / UX Designer & Front End Developer.
blog_description:  A UI / UX blog sharing tips, best practice, tutorials and more...
blog_url:          http://www.davidodey.com/blog.html